### ISSUE TITLE
Kommentarlinks führen nirgendwohin

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/schnitzler-bahr-static#10]
https://schnitzler-bahr.acdh.oeaw.ac.at/L041397.html
vgl.
Kommentar

**Comment by csae8092** [comment]
https://schnitzler-bahr.acdh.oeaw.ac.at/D041279.html/#bottom -> remove trainling slash 
https://schnitzler-bahr.acdh.oeaw.ac.at/D041279.html#bottom

**Comment by martinantonmueller** [comment]
@csae8092 vielen dank! mach’ ich. aber ich fürchte die ganze verweiserei habe ich nochmals anzusehen

**Comment by martinantonmueller** [comment]
solved with latest commit as suggested by @csae8092
